### ISSUE TITLE
Events are displayed in the wrong order

### ISSUE THREAD

**Issue by cstringer17** [prsm/frontend#1]
Events are displayed from furthest away to nearest, this should be the other way round.

![image](https://user-images.githubusercontent.com/22478341/137476344-6ae9f6d2-04e1-41aa-a535-60c8d49345af.png)

**Comment by jonasschultheiss** [comment]
denn mach grad no e reverse() an dere stell:
e.g.: `events.sort((a, b) => new Date(b.start) - new Date(a.start)).reverse();`
https://github.com/prsm/frontend/blob/33c6f09137329a2820a206cb9f8613baf22c33c5/components/Events.js#L5
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse
